# Generated by Django 3.1.4 on 2020-12-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarTransacciones', '0002_auto_20201229_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_alta', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaccion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
