# Generated by Django 3.1.4 on 2020-12-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarTransacciones', '0006_cierre_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='localidad',
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
