# Generated by Django 3.1.4 on 2021-01-05 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrarTransacciones', '0007_auto_20201230_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrarTransacciones.cliente'),
        ),
    ]
