# Generated by Django 3.1.4 on 2021-01-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarTransacciones', '0008_auto_20210104_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='egreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ingreso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
