# Generated by Django 3.1.4 on 2021-01-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrarTransacciones', '0009_auto_20210106_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='egreso',
            new_name='saldo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='ingreso',
        ),
    ]
