# Generated by Django 3.1.4 on 2021-01-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarTransacciones', '0010_auto_20210112_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='saldo',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
