# Generated by Django 3.1.4 on 2021-01-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrarTransacciones', '0011_auto_20210113_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='valor',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
